# SITE CONFIGURATION
title: Kenji T. Hayashi # your site title
author: Kenji T. Hayashi # You :P
description: > # Meta description of Homepage
  Personal website for Kenji T. Hayashi, Ph.D. student in the Kraft Lab, Department of Ecology and Evolutionary Biology, UCLA. Plant community assembly, coexistence, and biogeography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kthayashi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Kenji T. Hayashi
  links:
    - https://twitter.com/kthayashi
    # - https://www.facebook.com/xxxxx
    # - https://www.linkedin.com/in/xxxxx
    # - https://plus.google.com/xxxxx
    - https://github.com/kthayashi
    # - https://keybase.io/xxxxx

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  # - {name: 'Research', link: '/research'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'CV', link: '/cv'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Ph.D. Student in Ecology and Evolutionary Biology at UCLA

hero_img: posts/indian_paintbrush_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: # email for form submission

twitter_username: kthayashi # replace with your_twitter_username or comment to remove link from footer
github_username: kthayashi # replace with your_github_username or comment to remove link from footer
# instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
  # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
